CREATE TABLE dbo.RECIPE(
RECIPE_ID INT IDENTITY(1,1) PRIMARY KEY,
INGREDIENT_ID INT NOT NULL,
CREATED_ON DATETIME2 NOT NULL,
UPDATED_ON DATETIME2 NOT NULL
)


CREATE TABLE dbo.INGREDIENT (
INGREDIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
INGREDIENT_NAME NVARCHAR(MAX),
INGREDIENT_CLASS NVARCHAR(MAX),
CREATED_ON DATETIME2 NOT NULL,
UPDATED_ON DATETIME2 NOT NULL
)

CREATE TABLE dbo.MEAL_PLAN (
MEALPLAN_ID INT IDENTITY(1,1) PRIMARY KEY,
RECIPE_ID INT NOT NULL,
TYPEOF_MEAL NVARCHAR(MAX) NOT NULL,
DATEOF_MEAL DATE NOT NULL,
CREATED_ON DATETIME2 NOT NULL,
UPDATED_ON DATETIME2 NOT NULL)